spring:
  application:
    name: clientGateway

  freemarker:
    suffix: .html
  mvc:
    view:
      suffix: .html


# Define the port where the API gateway server would be running
server:
  port: 8762
security:
  sessions: never
